### ISSUE TITLE
java.lang.NoClassDefFoundError

### ISSUE THREAD

**Issue by mertcanekiz** [BennyQBD/DareEngine#9]
I get the following error when I try to run the ".run" file:

    Exception in thread "main" java.lang.NoClassDefFoundError: org/lwjgl/glfw/Callbacks
    	at engine.rendering.opengl.OpenGLDisplay.<init>(OpenGLDisplay.java:53)
    	at engine.Main.main(Main.java:124)
    Caused by: java.lang.ClassNotFoundException: org.lwjgl.glfw.Callbacks
	at java.net.URLClassLoader$1.run(URLClassLoader.java:366)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:355)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:354)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:425)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:308)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:358)
	... 2 more

Also, if I try to run make, I get a lot of LWJGL-related errors stating those symbols don't exist. I believe this is because you don't set the native location anywhere.

**Comment by BennyQBD** [comment]
This is because I haven't used the Makefile/run script since before I was using OpenGL in this project. As a result, they of course don't work anymore. Sorry for the confusion.

I've updated the project, and the latest version should have a working Makefile/run script. Let me know if it works for you.

**Comment by mertcanekiz** [comment]
Yes, it indeed works now by running make and run. Keep up the good work, Benny!
